run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable:
    - typecheck
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - nilerr
    - nolintlint
    - stylecheck
    - dupl
    - godox
    - prealloc
    - bodyclose
    - asasalint
    - contextcheck
    - errorlint
    - exhaustive
    - makezero
    - nilnil
    - predeclared
    - reassign
    - usestdlibvars
    - wastedassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    disable:
      - fieldalignment
    enable:
      - shadow
  
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  revive:
    rules:
      - name: exported
        severity: warning
      - name: error-return
      - name: error-naming
      - name: if-return
      - name: var-naming
      - name: package-comments
        severity: warning
      - name: indent-error-flow
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-strings
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id
  
  stylecheck:
    checks: ["all", "-ST1000"]
  
  dupl:
    threshold: 150
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - commentedOutCode
      - whyNoLint
      - dupImport
  
  godox:
    keywords:
      - FIXME
      - BUG
      - HACK
      - XXX

issues:
  exclude-dirs:
    - webserver/pkg/infrastructure/processor/loader
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gosec
    - path: proto/
      linters:
        - all
    - path: integration/
      linters:
        - errcheck
        - goconst
        - gosec
    - path: development_handler\.go
      linters:
        - gosec
    - path: dlopen_linux\.go
      linters:
        - dupImport
    - text: "G115:" # Integer overflow conversions are acceptable for protobuf int32
      linters:
        - gosec
    - text: "G114:" # HTTP serve timeouts are handled at server level
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true


