ARG TARGETARCH=amd64
ARG PROTO_VERSION=1.0.0
ARG CPP_VERSION=2.1.0
ARG GOLANG_VERSION=1.0.0

FROM scratch AS runtime
LABEL mock.runtime="true" \
      mock.targetarch="${TARGETARCH}" \
      mock.proto="${PROTO_VERSION}" \
      mock.cpp="${CPP_VERSION}" \
      mock.golang="${GOLANG_VERSION}"

