services:
  go-server:
    image: ${APP_IMAGE:-ghcr.io/josnelihurt/learning-cuda/app:latest-amd64}
    container_name: cuda-go-server
    restart: unless-stopped

    volumes:
      - ./data:/data:ro
      - ./config/config.production.yaml:/app/config/config.yaml:ro
      - /tmp:/tmp

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      iot-internal:
        aliases:
          - go-app
      public-wan:

  web-frontend:
    image: ${CUDA_WEB_FRONTEND_IMAGE:-ghcr.io/josnelihurt/learning-cuda/web-frontend:latest-amd64}
    container_name: cuda-web-frontend
    restart: unless-stopped
    depends_on:
      go-server:
        condition: service_healthy
    volumes:
      - ./data:/app/data:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public-wan"
      - "traefik.http.routers.go-server.rule=Host(`app-cuda-demo.josnelihurt.me`)"
      - "traefik.http.routers.go-server.entrypoints=https"
      - "traefik.http.routers.go-server.tls=true"
      - "traefik.http.routers.go-server.tls.certresolver=cloudflare"
      - "traefik.http.services.go-server.loadbalancer.server.port=80"
    networks:
      - iot-internal
      - public-wan

networks:
  public-wan:
    external: true
  iot-internal:
    external: true


