load("//bazel/defs:vulkan_glsl_to_spirv.bzl", "vulkan_kernel_embedded")

vulkan_kernel_embedded(
    name = "vk_grayscale",
    shader = "grayscale.comp",
)

vulkan_kernel_embedded(
    name = "vk_blur",
    shader = "blur.comp",
)
