load("//bazel/defs:opencl_cl_to_spirv.bzl", "opencl_kernel_embedded")

opencl_kernel_embedded(
    name = "cl_grayscale",
    cl_src = "cl_grayscale.cl",
)

opencl_kernel_embedded(
    name = "cl_blur",
    cl_src = "cl_blur.cl",
)
