services:
  grpc-server:
    image: ${GRPC_SERVER_IMAGE:-ghcr.io/josnelihurt-code/learning-cuda/grpc-server:latest-arm64}
    container_name: cuda-grpc-server
    restart: unless-stopped
    runtime: nvidia

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OTEL_LOGS_ENABLED=true
      - OTEL_LOGS_ENDPOINT=https://otel-cuda-demo.josnelihurt.me/v1/logs
      - OTEL_ENVIRONMENT=production

    ports:
      - "60061:60061"

volumes: {}