cc_library(
    name = "grayscale_processor",
    srcs = ["grayscale_processor.cpp"],
    hdrs = ["grayscale_processor.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//cpp_accelerator/domain/interfaces",
        "//cpp_accelerator/domain/interfaces:processors",
        "@spdlog",
    ],
)

