server:
  port: ":8080"
  hot_reload_enabled: false  
  web_root_path: "webserver/web"

stream:
  transport_format: "json"  # or "binary" - protobuf serialization format
  websocket_endpoint: "/ws"
  # Future: grpc_endpoint: ":50051"

# Feature flags (future: connect to LaunchDarkly/Unleash)
# Unleash is self-hosted option, LaunchDarkly is cloud-based
features:
  use_binary_protocol: true
  enable_grpc_streaming: false

