server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: cpp-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: cpp-logs
          source: cpp
          __path__: /tmp/cppaccelerator.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: "2006-01-02T15:04:05.000Z"
      - output:
          source: message

  - job_name: go-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: host-logs
          source: go
          __path__: /tmp/goserver.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            time: time
      - labels:
          level:
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: message

