---
- name: Clone repository 
  git:
    repo: "https://github.com/josnelihurt/learning-cuda.git"
    dest: "/opt/josnelihurt/cuda-learning"
    version: "{{ repo_branch }}"
    update: yes
    force: yes
  become_user: "{{ deployment_user }}"

- name: Copy modified files to remote repository
  copy:
    src: "/home/jrb/code/cuda-learning/"
    dest: "/opt/josnelihurt/cuda-learning/"
    owner: "{{ deployment_user }}"
    group: "{{ deployment_group }}"
    mode: '0644'
    directory_mode: '0755'
  become_user: "{{ deployment_user }}"
  ignore_errors: yes

- name: Set proper ownership on synced files
  file:
    path: "/opt/josnelihurt/cuda-learning"
    owner: "{{ deployment_user }}"
    group: "{{ deployment_group }}"
    recurse: yes
  become_user: "{{ deployment_user }}"

- name: Display deployment status
  debug:
    msg:
      - "Repository cloned and synced successfully"
      - "Location: /opt/josnelihurt/cuda-learning"
      - "Local changes synchronized"
      - "Next steps:"
      - "  1. cd /opt/josnelihurt/cuda-learning"
      - "  2. docker compose -f docker-compose.yml build --pull"
      - "  3. docker compose --profile production up -d"
      - "Note: Dockerfile supports multi-platform builds automatically"
