load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "domain",
    srcs = [
        "feature_flag.go",
        "image_repository.go",
    ],
    importpath = "github.com/jrb/cuda-learning/webserver/pkg/domain",
    visibility = ["//visibility:public"],
)

