cc_library(
    name = "i_control_port",
    hdrs = ["control/i_control_port.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "i_media_session",
    hdrs = ["media/i_media_session.h"],
    visibility = ["//visibility:public"],
)
