services:
  learning-cuda-go-api:
    image: ${APP_IMAGE:-ghcr.io/josnelihurt-code/learning-cuda/app:latest-amd64}
    container_name: cuda-go-server
    restart: unless-stopped

    volumes:
      - ./data:/data:ro
      - ./config/config.production.yaml:/app/config/config.yaml:ro
      - /tmp:/tmp

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      iot-internal:
        aliases:
          - learning-cuda-go-api
      public-wan:

  learning-cuda-frontend:
    image: ${CUDA_WEB_FRONTEND_IMAGE:-ghcr.io/josnelihurt-code/learning-cuda/web-frontend:latest-amd64}
    container_name: cuda-web-frontend
    restart: unless-stopped
    depends_on:
      learning-cuda-go-api:
        condition: service_healthy
    volumes:
      - ./data:/app/data:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public-wan"
      - "traefik.http.routers.learning-cuda-frontend.rule=Host(`cuda-demo.lab.josnelihurt.me`)"
      - "traefik.http.routers.learning-cuda-frontend.entrypoints=https"
      - "traefik.http.routers.learning-cuda-frontend.tls=true"
      - "traefik.http.services.learning-cuda-frontend.loadbalancer.server.port=80"
    networks:
      - iot-internal
      - public-wan

