#!/bin/bash
# Generate version.js with current git commit hash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
VERSION_FILE="$PROJECT_ROOT/webserver/web/static/js/version.js"

cd "$PROJECT_ROOT"

# Get git commit hash (short)
GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Generate version.js
cat > "$VERSION_FILE" << EOF
// Auto-generated version file - DO NOT EDIT MANUALLY
// Generated by scripts/generate-version.sh on $BUILD_TIME

const APP_VERSION = '$GIT_HASH';
const APP_BRANCH = '$GIT_BRANCH';
const BUILD_TIME = '$BUILD_TIME';

console.log(\`Build: \${APP_VERSION} (\${APP_BRANCH}) - \${BUILD_TIME}\`);
EOF

echo "Generated version.js: $GIT_HASH ($GIT_BRANCH)"
