ARG CUDA_VERSION=12.5.1
ARG UBUNTU_VERSION=24.04
ARG TARGETARCH=amd64

FROM scratch AS bazel-base
LABEL mock.component="bazel-base" \
      mock.cuda="${CUDA_VERSION}" \
      mock.ubuntu="${UBUNTU_VERSION}" \
      mock.targetarch="${TARGETARCH}"

