ARG UBUNTU_VERSION=24.04
ARG TARGETARCH=amd64
ARG GO_VERSION=1.24.0

FROM scratch AS integration-tests-base
LABEL mock.component="integration-tests-base" \
      mock.go_version="${GO_VERSION}" \
      mock.targetarch="${TARGETARCH}" \
      mock.ubuntu="${UBUNTU_VERSION}"

