#version 450

layout(local_size_x = 64) in;

layout(binding = 0) buffer BufferA {
    float data_A[];
};

layout(binding = 1) buffer BufferB {
    float data_B[];
};

layout(binding = 2) buffer BufferC {
    float data_C[];
};

layout(push_constant) uniform PushConstants {
    uint n;
};

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i < n) {
        data_C[i] = data_A[i] + data_B[i];
    }
}
