---
- name: Deploy CUDA Learning Application to Jetson Nano
  hosts: jetson
  become: yes
  gather_facts: yes
  
  vars:
    app_name: cuda-learning
    app_directory: "/opt/josnelihurt/cuda-learning"
    repo_url: "https://github.com/josnelihurt/learning-cuda.git"
    repo_branch: "main"
    deployment_user: "jrb"
    deployment_group: "jrb"
    
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      
  roles:
    - role: setup
      tags: [setup, all]
      
    - role: application
      tags: [application, all]
      
    - role: docker-deploy
      tags: [docker-deploy, all]
