cc_library(
    name = "config",
    srcs = ["config_manager.cpp"],
    hdrs = [
        "config_manager.h",
        "models/program_config.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//core:result",
        "@lyra//:lyra",
        "@spdlog//:spdlog",
    ],
)
